# Generated by Django 4.1.6 on 2023-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgame',
            name='privacy',
            field=models.CharField(default='private', max_length=100),
        ),
    ]
