# Generated by Django 4.1.6 on 2023-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0004_alter_cardgame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgame',
            name='privacy',
            field=models.CharField(choices=[('PU', 'public'), ('PR', 'private')], default='private', max_length=10),
        ),
    ]
