# Generated by Django 4.1.6 on 2023-03-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0005_alter_cardgame_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgame',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
