# Generated by Django 4.1.6 on 2023-03-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0008_remove_game_cardgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='anansiapp.gameplayer'),
        ),
    ]
