# Generated by Django 4.1.6 on 2023-03-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0007_alter_cardgame_privacy'),
        ('anansiapp', '0009_alter_game_creator'),
    ]

    operations = [
    ]
