# Generated by Django 4.1.6 on 2023-03-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anansiapp', '0010_merge_20230330_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('gap_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.cardgame')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.cardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloze_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.clozecard')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='cardgame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anansiapp.cardgame'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='anansiapp.gameplayer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoundResponseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='anansiapp.gameplayer')),
                ('response_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.responsecard')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='anansiapp.round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.game'),
        ),
        migrations.AddField(
            model_name='round',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_master', to='anansiapp.gameplayer'),
        ),
        migrations.AddField(
            model_name='round',
            name='round_response_card_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_response_card_winner', to='anansiapp.roundresponsecard'),
        ),
        migrations.CreateModel(
            name='GamePlayerResponseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.gameplayer')),
                ('response_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.responsecard')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteCardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.cardgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
