# Generated by Django 4.1.6 on 2023-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0011_clozecard_responsecard_round_game_cardgame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='anansiapp.gameplayer'),
        ),
    ]
