# Generated by Django 4.1.6 on 2023-03-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0011_alter_game_creator_alter_game_winner'),
        ('anansiapp', '0011_clozecard_responsecard_round_game_cardgame_and_more'),
    ]

    operations = [
    ]
