# Generated by Django 4.1.6 on 2023-04-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0012_alter_game_creator'),
        ('anansiapp', '0012_merge_20230330_1422'),
    ]

    operations = [
    ]
