# Generated by Django 4.1.6 on 2023-04-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0013_merge_20230419_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='anansiapp.gameplayer'),
        ),
    ]
