# Generated by Django 4.1.6 on 2023-04-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0013_merge_20230405_1542'),
        ('anansiapp', '0014_alter_game_winner'),
    ]

    operations = [
    ]
