# Generated by Django 4.1.6 on 2023-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0015_merge_0013_merge_20230405_1542_0014_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
