# Generated by Django 4.1.6 on 2023-05-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anansiapp', '0015_merge_0013_merge_20230405_1542_0014_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clozecard',
            old_name='cardgame',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='cardgame',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='responsecard',
            old_name='cardgame',
            new_name='deck',
        ),
        migrations.RenameModel(
            old_name='CardGame',
            new_name='Deck',
        ),
        migrations.DeleteModel(
            name='FavouriteCardGame',
        ),
        migrations.AddField(
            model_name='favouritedeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anansiapp.deck'),
        ),
        migrations.AddField(
            model_name='favouritedeck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
