# Generated by Django 4.1.6 on 2023-04-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0016_game_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='round_response_card_winner',
        ),
    ]
