# Generated by Django 4.1.6 on 2023-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0018_remove_game_creator_remove_game_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_response_card_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_response_card_winner', to='anansiapp.roundresponsecard'),
        ),
    ]
