# Generated by Django 4.1.6 on 2023-05-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0016_favouritedeck_rename_cardgame_clozecard_deck_and_more'),
        ('anansiapp', '0019_round_round_response_card_winner'),
    ]

    operations = [
    ]
