# Generated by Django 4.1.6 on 2023-05-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anansiapp', '0020_merge_20230501_1528'),
        ('anansiapp', '0020_merge_20230501_1641'),
    ]

    operations = [
    ]
