# Generated by Django 4.1.6 on 2023-05-03 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anansiapp', '0021_merge_20230501_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clozecard',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='favouritedeck',
            unique_together={('user', 'deck')},
        ),
    ]
